# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - outlook-onsend-site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'outlook-onsend-site'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d6e78013723e499692cd7e495bab2fe6 }}
        package: .